# Generated by Django 5.1.6 on 2025-03-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True, db_index=True, unique=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('air_quality', models.FloatField()),
            ],
        ),
    ]
