# Generated by Django 5.1.6 on 2025-03-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='air_quality',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
