# Generated by Django 5.1.6 on 2025-03-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_sensor', '0002_alter_log_air_quality_alter_log_humidity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='timestamps',
            new_name='timestamp',
        ),
    ]
